/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves user's contexts. */
        get: operations["ContextsController_listContexts"];
        put?: never;
        /** Creates a new context. */
        post: operations["ContextsController_createContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contexts/{contextId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves an specific context. */
        get: operations["ContextsController_getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a list of contexts to display in the marketplace section. */
        get: operations["MarketplaceController_listMarketplaceItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/{slugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the context information with the current version content. */
        get: operations["MarketplaceController_getMarketplaceContextBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contexts/{contextId}/context-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a list of context versions within a context. */
        get: operations["ContextVersionsController_listContextVersions"];
        put?: never;
        /** Creates a new context version within a context. */
        post: operations["ContextVersionsController_createContextVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contexts/{contextId}/context-versions/{contextVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes a context version. */
        delete: operations["ContextVersionsController_deleteContextVersion"];
        options?: never;
        head?: never;
        /** Updates a context version. */
        patch: operations["ContextVersionsController_updateContextVersion"];
        trace?: never;
    };
    "/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all user's catalog. */
        get: operations["CatalogsController_listCatalog"];
        put?: never;
        /** Creates a new catalog. */
        post: operations["CatalogsController_createCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogs/{catalogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes a catalog. */
        delete: operations["CatalogsController_deleteCatalog"];
        options?: never;
        head?: never;
        /** Updates a catalog. */
        patch: operations["CatalogsController_updateCatalog"];
        trace?: never;
    };
    "/catalogs/{catalogId}/contexts-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inserts a context version in a catalog. */
        post: operations["CatalogContextsController_insertContextVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogs/{catalogId}/contexts-versions/{contextVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a context version from a catalog. */
        delete: operations["CatalogContextsController_deleteContextVersion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account. */
        post: operations["AuthController_registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate a user account. */
        post: operations["AuthController_authenticateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request validation for an account. */
        post: operations["AuthController_requestValidation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an account. */
        post: operations["AuthController_verifyUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if the user is authenticated. */
        get: operations["AuthController_checkUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the user tokens. */
        get: operations["TokensController_listTokens"];
        put?: never;
        /** Creates a new token. */
        post: operations["TokensController_createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deletes a token. */
        delete: operations["TokensController_deleteToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the catalog information. */
        get: operations["McpController_listInformation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of prompts of a catalog. */
        get: operations["McpController_listPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of tools of a catalog. */
        get: operations["McpController_listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of resources of a catalog. */
        get: operations["McpController_listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the full content of a resource. */
        get: operations["McpController_readResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp/download/{slugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the full content of a context version. */
        get: operations["McpController_downloadContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The type of the context.
         * @enum {string}
         */
        ContextType: "public" | "private";
        CreateContextBody: {
            /** @description The name of the context. */
            name: string;
            /** @description The description of the context. */
            description: string;
            /** @description The slug of the context. */
            slug: string;
            /** @description The type of the context. */
            type: components["schemas"]["ContextType"];
        };
        Context: {
            /** @description The id of the entity. */
            id: number;
            /**
             * Format: date-time
             * @description The creation date of the entity.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The update date of the entity.
             */
            updatedAt: string;
            /** @description The name of the context. */
            name: string;
            /** @description The description of the context. */
            description: string;
            /** @description The slug of the context. */
            slug: string;
            /** @description The type of the context. */
            type: components["schemas"]["ContextType"];
        };
        ListContextsResponse: {
            /** @description The contexts. */
            items: components["schemas"]["Context"][];
            /** @description Whether there are more contexts. */
            hasMore: boolean;
            /** @description The next page url. */
            nextUrl?: string;
        };
        PromptArgument: {
            /** @description The name of the argument. */
            name: string;
            /** @description The description of the argument. */
            description?: string;
            /**
             * @description The required status of the argument.
             * @default false
             */
            required: boolean;
        };
        MarketplaceContextVersionPrompt: {
            /** @description The name of the prompt. */
            name: string;
            /** @description The title of the prompt. */
            title: string;
            /** @description The description of the prompt. */
            description: string;
            /** @description The arguments of the prompt. */
            arguments: components["schemas"]["PromptArgument"][];
        };
        MarketplaceContextVersionResource: {
            /** @description The uri of the resource. */
            uri: string;
            /** @description The name of the resource. */
            name: string;
            /** @description The title of the resource. */
            title: string;
            /** @description The description of the resource. */
            description: string;
            /** @description The mime type of the resource. */
            mimeType: string;
            /**
             * @description The size of the resource.
             * @default null
             */
            size: number | null;
            /** @description The id of the resource. UUID. */
            id: string;
        };
        MarketplaceContextVersionTool: {
            /** @description The tool's name. */
            name: string;
            /** @description The title of the tool, human readable. For display purposes. */
            title: string;
            /** @description The description of the resource, human readable. */
            description: string;
            /** @description The id of the resource. UUID. */
            id: string;
        };
        MarketplaceContextVersion: {
            /** @description The id of the entity. */
            id: number;
            /** @description The version of the context version. */
            version: string;
            /**
             * @description The description of the context version.
             * @default null
             */
            description: string | null;
            /** @description The prompts of the context version. */
            prompts: components["schemas"]["MarketplaceContextVersionPrompt"][];
            /** @description The resources of the context version. */
            resources: components["schemas"]["MarketplaceContextVersionResource"][];
            /** @description The tools of the context version. */
            tools: components["schemas"]["MarketplaceContextVersionTool"][];
        };
        MarketplaceContext: {
            /** @description The id of the entity. */
            id: number;
            /**
             * Format: date-time
             * @description The creation date of the entity.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The update date of the entity.
             */
            updatedAt: string;
            /** @description The name of the context. */
            name: string;
            /** @description The description of the context. */
            description: string;
            /** @description The slug of the context. */
            slug: string;
            /** @description The type of the context. */
            type: components["schemas"]["ContextType"];
            /** @description The versions of the context. */
            contextVersions: components["schemas"]["MarketplaceContextVersion"][];
        };
        ListMarketplaceItemsResponse: {
            /** @description The marketplace contexts. */
            items: components["schemas"]["MarketplaceContext"][];
            /** @description Whether there are more marketplace contexts. */
            hasMore: boolean;
            /** @description The next page url. */
            nextUrl?: string;
        };
        /**
         * @description The status of the context version.
         * @enum {string}
         */
        ContextVersionStatus: "draft" | "internal" | "published" | "archived";
        /**
         * @description The content of the message.
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * @description The content of the message.
         * @enum {string}
         */
        PromptMessageContentType: "text" | "image" | "audio" | "resource" | "webhook";
        PromptMessageContent: {
            /** @description The content of the message. */
            type: components["schemas"]["PromptMessageContentType"];
            /** @description The content of the message, only use if `type` is `PromptMessageContentType.TEXT`. */
            text?: string;
            /** @description The url the prompt will use to generate the content of the message, only use if `type` is `PromptMessageContentType.WEBHOOK`. */
            url?: string;
            /** @description The mime type of the `data` member, only use if `type` is not `PromptMessageContentType.TEXT`. */
            mimeType?: string;
            /** @description The content of the message, only use if `type` is not `PromptMessageContentType.TEXT`. For images and audios, the base64 encoded data. */
            data?: string;
        };
        PromptMessage: {
            /** @description The content of the message. */
            role: components["schemas"]["MessageRole"];
            /** @description The content of the message. */
            content: components["schemas"]["PromptMessageContent"];
            /**
             * @description The description of the message.
             * @default null
             */
            description: string | null;
        };
        Prompt: {
            /** @description The name of the prompt. */
            name: string;
            /** @description The title of the prompt. */
            title: string;
            /** @description The description of the prompt. */
            description: string;
            /** @description The arguments of the prompt. */
            arguments: components["schemas"]["PromptArgument"][];
            /** @description The messages of the prompt. */
            messages: components["schemas"]["PromptMessage"][];
        };
        ResourceAnnotation: {
            /**
             * @description The role of the audience.
             * @default null
             */
            audience: components["schemas"]["MessageRole"][] | null;
            /**
             * @description The priority of the audience.
             * @default null
             */
            priority: number | null;
            /**
             * @description The last modified of the resource.
             * @default null
             */
            lastModified: string | null;
        };
        Resource: {
            /** @description The uri of the resource. */
            uri: string;
            /** @description The name of the resource. */
            name: string;
            /** @description The title of the resource. */
            title: string;
            /** @description The description of the resource. */
            description: string;
            /** @description The mime type of the resource. */
            mimeType: string;
            /**
             * @description The size of the resource.
             * @default null
             */
            size: number | null;
            /**
             * @description The text of the resource. Only for text/markdown or text mime types. Ups to 5MB.
             * @default null
             */
            text: string | null;
            /**
             * @description The blob of the resource. Only for binary files, it must be base64 encoded.
             * @default null
             */
            blob: string | null;
            /**
             * @description The annotations of the resource.
             * @default null
             */
            annotations: components["schemas"]["ResourceAnnotation"] | null;
            /** @description The id of the resource. UUID. */
            id: string;
        };
        /**
         * @description The operating system to use for the execution strategy.
         * @enum {string}
         */
        ToolLocalOs: "darwin" | "linux" | "windows";
        /**
         * @description The shell to use for the execution strategy.
         * @enum {string}
         */
        ToolLocalShellType: "bash" | "powershell" | "cmd" | "zsh" | "sh";
        ToolStrategyLocalEnvironment: {
            /** @description The operating system to use for the execution strategy. */
            os: components["schemas"]["ToolLocalOs"][];
            /** @description The shell to use for the execution strategy. */
            shell: components["schemas"]["ToolLocalShellType"];
            /** @description The required applications to use for the execution strategy. */
            requires: string[];
        };
        /**
         * @description The format the response must be in to be considered successful.
         * @enum {string}
         */
        ToolLocalOutputFormat: "raw" | "json" | "csv" | "file";
        ToolStrategyLocalSuccessCriteria: {
            /**
             * @description The exit code the tool must return to be considered successful.
             * @default null
             */
            exitCode: number | null;
            /**
             * @description The patterns the response must match to be considered successful.
             * @default null
             */
            responseMatches: string[] | null;
            /**
             * @description The format the response must be in to be considered successful.
             * @default null
             */
            outputFormat: components["schemas"]["ToolLocalOutputFormat"] | null;
            /**
             * @description The output file path the response must be in to be considered successful. Only use it if `outputFormat` is `ToolLocalOutputFormat.FILE`.
             * @default null
             */
            outputFilePath: string | null;
        };
        /**
         * @description The placeholders to use for the execution strategy.
         * @enum {string}
         */
        ToolLocalWorkingDirectoryType: "temp" | "workspace" | "repo_root" | "cwd" | "project_root";
        ToolStrategyLocalConfig: {
            /**
             * @description Whether to run the tool in a shell or not. Default: `false`.
             * @default false
             */
            runInShell: boolean;
            /** @description The commands to execute the tool. Only use it if `runInShell` is `false`. */
            commands: string[];
            /** @description The environment to use for the execution strategy. */
            environment: components["schemas"]["ToolStrategyLocalEnvironment"];
            /**
             * @description The timeout to use for the execution strategy.
             * @default null
             */
            timeout: number | null;
            /**
             * @description The working directory to use for the execution strategy.
             * @default null
             */
            workingDirectory: string | null;
            /** @description The maximum output size to use for the execution strategy. */
            maxOutputSize: number;
            /** @description The cooldown time to use for the execution strategy. Used to avoid LLM tool spam. */
            cooldownMs: number;
            /**
             * @description The success criteria to use for the execution strategy.
             * @default null
             */
            successCriteria: components["schemas"]["ToolStrategyLocalSuccessCriteria"] | null;
            /**
             * @description Whether the tool is deterministic or not. Default: `false`.
             * @default false
             */
            deterministic: boolean;
            /** @description The placeholders to use for the execution strategy. */
            placeholders: components["schemas"]["ToolLocalWorkingDirectoryType"][];
            /**
             * @description The output mapping for the execution strategy.
             * @default null
             */
            outputMapping: {
                [key: string]: string;
            } | null;
        };
        ToolStrategyWebhookConfig: {
            /** @description The webhook url to use for the execution strategy. */
            url: string;
        };
        /**
         * @description The status of the tool.
         * @enum {string}
         */
        ToolStatus: "active" | "inactive";
        /**
         * @description The type of execution strategy.
         * @enum {string}
         */
        ToolExecutionType: "local" | "webhook";
        ToolExecutionStrategy: {
            /** @description The type of execution strategy. */
            type: components["schemas"]["ToolExecutionType"];
            /** @description The configuration for the execution strategy. */
            config: components["schemas"]["ToolStrategyLocalConfig"] | components["schemas"]["ToolStrategyWebhookConfig"];
            /**
             * @description The priority of the execution strategy. Number between 0 and 1.
             * @default null
             */
            priority: number | null;
        };
        ToolAnnotation: {
            /**
             * @description The role of the audience.
             * @default null
             */
            audience: components["schemas"]["MessageRole"][] | null;
            /**
             * @description The priority of the audience.
             * @default null
             */
            priority: number | null;
            /**
             * @description The last modified of the resource.
             * @default null
             */
            lastModified: string | null;
        };
        ToolPermissions: {
            /** @description Whether the tool can access the network or not. */
            network?: boolean;
            /** @description Whether the tool can write to the filesystem or not. */
            filesystemWrite?: boolean;
            /** @description Whether the tool can read from the filesystem or not. */
            filesystemRead?: boolean;
            /** @description Whether the tool can run privileged commands or not. */
            privileged?: boolean;
        };
        Tool: {
            /** @description The tool's name. */
            name: string;
            /** @description The title of the tool, human readable. For display purposes. */
            title: string;
            /** @description The description of the resource, human readable. */
            description: string;
            /** @description The id of the resource. UUID. */
            id: string;
            /** @description The status of the tool. */
            status: components["schemas"]["ToolStatus"];
            /**
             * @description The JSON schema defining expected parameters.
             * @default null
             */
            inputSchema: Record<string, never> | null;
            /**
             * @description The JSON schema defining expected output format.
             * @default null
             */
            outputSchema: Record<string, never> | null;
            /** @description The execution strategies of the tool. */
            execution: components["schemas"]["ToolExecutionStrategy"][];
            /**
             * @description The annotations of the tool.
             * @default null
             */
            annotations: components["schemas"]["ToolAnnotation"] | null;
            /** @description The permissions of the tool. */
            permissions?: components["schemas"]["ToolPermissions"];
        };
        Environment: {
            /** @description The id of the environment. UUID. */
            id: string;
            /** @description The name of the environment variable. Must be in upper case snake case. */
            name: string;
            /** @description The description of the environment variable. */
            description: string;
            /**
             * @description The default value of the environment variable. Required if `modifiable` is `false`.
             * @default null
             */
            default: string | null;
            /**
             * @description Whether the environment variable is modifiable by the client or not. Default: `true`.
             * @default true
             */
            modifiable: boolean;
            /**
             * @description Whetever the client is required to set the value of the environment variable. Default: `false`.
             * @default false
             */
            required: boolean;
        };
        ContextVersion: {
            /** @description The id of the entity. */
            id: number;
            /**
             * Format: date-time
             * @description The creation date of the entity.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The update date of the entity.
             */
            updatedAt: string;
            /** @description The version of the context version. */
            version: string;
            /**
             * @description The description of the context version.
             * @default null
             */
            description: string | null;
            /** @description The status of the context version. */
            status: components["schemas"]["ContextVersionStatus"];
            /** @description The prompts of the context version. */
            prompts: components["schemas"]["Prompt"][];
            /** @description The resources of the context version. */
            resources: components["schemas"]["Resource"][];
            /** @description The tools of the context version. */
            tools: components["schemas"]["Tool"][];
            /** @description The environments of the context version. */
            variables: components["schemas"]["Environment"][];
            /** @description The context id of the context. */
            contextId: number;
            /**
             * @description The context of the context version.
             * @default {}
             */
            context: components["schemas"]["Context"];
        };
        GetMarketplaceContextBySlugResponse: {
            /** @description The context of the context version. */
            context: components["schemas"]["Context"];
            /** @description The context version of the context. */
            contextVersion: components["schemas"]["ContextVersion"];
            /** @description The versions of the context, for display reasons. */
            contextVersions: components["schemas"]["MarketplaceContextVersion"][];
        };
        CreateContextVersionBody: {
            /** @description The version of the context version. */
            version: string;
            /**
             * @description The description of the context version.
             * @default null
             */
            description: string | null;
            /** @description The status of the context version. */
            status: components["schemas"]["ContextVersionStatus"];
            /** @description The prompts of the context version. */
            prompts: components["schemas"]["Prompt"][];
            /** @description The resources of the context version. */
            resources: components["schemas"]["Resource"][];
            /** @description The tools of the context version. */
            tools: components["schemas"]["Tool"][];
        };
        ListContextVersionsResponse: {
            /** @description The context versions. */
            items: components["schemas"]["ContextVersion"][];
            /** @description Whether there are more context versions. */
            hasMore: boolean;
            /** @description The next page url. */
            nextUrl?: string;
        };
        UpdateContextVersionBody: {
            /**
             * @description The description of the context version.
             * @default null
             */
            description: string | null;
            /** @description The status of the context version. */
            status?: components["schemas"]["ContextVersionStatus"];
            /** @description The prompts of the context version. */
            prompts?: components["schemas"]["Prompt"][];
            /** @description The resources of the context version. */
            resources?: components["schemas"]["Resource"][];
            /** @description The tools of the context version. */
            tools?: components["schemas"]["Tool"][];
        };
        GenericResponse: {
            /**
             * @description The success of the operation.
             * @example true
             */
            success: boolean;
        };
        /**
         * @description The status of the catalog.
         * @enum {string}
         */
        CatalogStatus: "active" | "inactive";
        CreateCatalogBody: {
            /** @description The name of the catalog. */
            name: string;
            /**
             * @description The description of the catalog.
             * @default null
             */
            description: string;
            /** @description The slug of the catalog. */
            slug: string;
            /** @description The status of the catalog. */
            status: components["schemas"]["CatalogStatus"];
        };
        Catalog: {
            /** @description The id of the entity. */
            id: number;
            /**
             * Format: date-time
             * @description The creation date of the entity.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The update date of the entity.
             */
            updatedAt: string;
            /** @description The name of the catalog. */
            name: string;
            /**
             * @description The description of the catalog.
             * @default null
             */
            description: string;
            /** @description The slug of the catalog. */
            slug: string;
            /**
             * @description The context versions id of the catalog.
             * @default []
             */
            contextVersionsId: number[];
            /** @description The status of the catalog. */
            status: components["schemas"]["CatalogStatus"];
            /**
             * @description The context versions of the catalog. Only if the request was done with query `extended=yes`.
             * @default []
             */
            contextVersions: components["schemas"]["ContextVersion"][];
        };
        /** @enum {string} */
        ExtendType: "yes" | "no";
        ListCatalogsResponse: {
            /** @description The catalogs. */
            items: components["schemas"]["Catalog"][];
            /** @description Whether there are more catalogs. */
            hasMore: boolean;
            /** @description The next page url. */
            nextUrl?: string;
        };
        UpdateCatalogBody: {
            /** @description The name of the catalog. */
            name?: string;
            /**
             * @description The description of the catalog.
             * @default null
             */
            description: string;
            /** @description The status of the catalog. */
            status?: components["schemas"]["CatalogStatus"];
        };
        InsertContextVersionBody: {
            /** @description The id of the context version. */
            contextVersionId: number;
        };
        RegisterUserBody: {
            /** @description The user's email. */
            email: string;
            /** @description The password of the new user account. */
            password: string;
        };
        AuthenticateUserBody: {
            /** @description The user's email. */
            email: string;
            /** @description The password of the new user account. */
            password: string;
        };
        AuthenticateUserResponse: {
            /** @description The access token of the authenticated user. */
            accessToken: string;
        };
        VerifyUserBody: {
            /** @description The code to use to try verify the user. */
            code: string;
        };
        /**
         * @description The access type of the token.
         * @enum {string}
         */
        TokenAccessType: "mcp" | "api";
        CreateTokenBody: {
            /** @description The description of the token. */
            description: string;
            /** @description The access type of the token. */
            accessType: components["schemas"]["TokenAccessType"];
        };
        Token: {
            /** @description The id of the entity. */
            id: number;
            /**
             * Format: date-time
             * @description The creation date of the entity.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The update date of the entity.
             */
            updatedAt: string;
            /** @description The description of the token. */
            description: string;
            /** @description The token. */
            key: string;
        };
        ListTokensResponse: {
            /** @description The tokens. */
            items: components["schemas"]["Token"][];
            /** @description Whether there are more tokens. */
            hasMore: boolean;
            /** @description The next page url. */
            nextUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ContextsController_listContexts: {
        parameters: {
            query: {
                /** @description The previous query last item id. */
                lastId?: number;
                /** @description The limit of the page. */
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contexts of the user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListContextsResponse"];
                };
            };
        };
    };
    ContextsController_createContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContextBody"];
            };
        };
        responses: {
            /** @description The created context. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateContextBody"];
                };
            };
        };
    };
    ContextsController_getContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Context"];
                };
            };
            /** @description Context not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarketplaceController_listMarketplaceItems: {
        parameters: {
            query: {
                /** @description The previous query last item id. */
                lastId?: number;
                /** @description The limit of the page. */
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contexts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMarketplaceItemsResponse"];
                };
            };
        };
    };
    MarketplaceController_getMarketplaceContextBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slugId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contexts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMarketplaceContextBySlugResponse"];
                };
            };
        };
    };
    ContextVersionsController_listContextVersions: {
        parameters: {
            query: {
                /** @description The previous query last item id. */
                lastId?: number;
                /** @description The limit of the page. */
                size: number;
            };
            header?: never;
            path: {
                contextId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The context versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListContextVersionsResponse"];
                };
            };
        };
    };
    ContextVersionsController_createContextVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContextVersionBody"];
            };
        };
        responses: {
            /** @description The created context version. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateContextVersionBody"];
                };
            };
        };
    };
    ContextVersionsController_deleteContextVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextVersionId: number;
                contextId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whetever the context version was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    ContextVersionsController_updateContextVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextId: number;
                contextVersionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContextVersionBody"];
            };
        };
        responses: {
            /** @description The updated context version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextVersion"];
                };
            };
            /** @description Cannot update a published context version. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogsController_listCatalog: {
        parameters: {
            query: {
                /** @description Whatever the response must arrives with extended information or not. */
                extend?: components["schemas"]["ExtendType"];
                /** @description The previous query last item id. */
                lastId?: number;
                /** @description The limit of the page. */
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalogs of the user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCatalogsResponse"];
                };
            };
        };
    };
    CatalogsController_createCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCatalogBody"];
            };
        };
        responses: {
            /** @description The catalogs of the user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    CatalogsController_deleteCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalogs of the user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    CatalogsController_updateCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCatalogBody"];
            };
        };
        responses: {
            /** @description The updated catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    CatalogContextsController_insertContextVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InsertContextVersionBody"];
            };
        };
        responses: {
            /** @description The updated catalog. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    CatalogContextsController_deleteContextVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contextVersionId: number;
                catalogId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    AuthController_registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserBody"];
            };
        };
        responses: {
            /** @description User registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_authenticateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthenticateUserBody"];
            };
        };
        responses: {
            /** @description User authenticated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticateUserResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestValidation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation request sent successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    AuthController_verifyUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyUserBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticateUserResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_checkUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TokensController_listTokens: {
        parameters: {
            query: {
                /** @description The previous query last item id. */
                lastId?: number;
                /** @description The limit of the page. */
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The created tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTokensResponse"];
                };
            };
        };
    };
    TokensController_createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenBody"];
            };
        };
        responses: {
            /** @description The created token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    TokensController_deleteToken: {
        parameters: {
            query: {
                tokenId: number;
            };
            header?: never;
            path: {
                tokenId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wathever the token was deleted or not. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericResponse"];
                };
            };
        };
    };
    McpController_listInformation: {
        parameters: {
            query: {
                /** @description The catalog slug. */
                catalogSlug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalog information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    McpController_listPrompts: {
        parameters: {
            query: {
                /** @description The catalog slug. */
                catalogSlug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every prompt within the catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"][];
                };
            };
        };
    };
    McpController_listTools: {
        parameters: {
            query: {
                /** @description The catalog slug. */
                catalogSlug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every tool within the catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tool"][];
                };
            };
        };
    };
    McpController_listResources: {
        parameters: {
            query: {
                /** @description The catalog slug. */
                catalogSlug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every resource within the catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
        };
    };
    McpController_readResource: {
        parameters: {
            query: {
                /** @description The catalog slug. */
                catalogSlug: string;
            };
            header?: never;
            path: {
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resource was found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description The resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpController_downloadContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slugId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The context version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextVersion"];
                };
            };
        };
    };
}
